_wandb:
    value:
        cli_version: 0.21.0
        e:
            3rujtpd3qtjpm2w84ynxc0po4rip11pl:
                codePath: Ayna_Assignment/train.py
                codePathLocal: train.py
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "82086207488"
                        used: "69084876800"
                email: kpaishwarya001@gmail.com
                executable: /usr/bin/python3
                host: aishwarya-IdeaPad-3-15IIL05
                memory:
                    total: "3652538368"
                os: Linux-5.15.0-41-generic-x86_64-with-glibc2.35
                program: /home/aishwarya/Documents/Ayna_Assignment/train.py
                python: CPython 3.10.6
                root: /home/aishwarya/Documents/Ayna_Assignment
                startedAt: "2025-08-04T14:52:47.335509Z"
                writerId: 3rujtpd3qtjpm2w84ynxc0po4rip11pl
        m: []
        python_version: 3.10.6
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
            "4": 3.10.6
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 8
epochs:
    value: 30
img_size:
    value: 128
lr:
    value: 0.0001
